// js/aircraft-data.js

export const AIRLINES = {
  AFR: "Air France",
  HOP: "Air France Hop",
  TVF: "Transavia France",
  FBU: "French Bee",
  CRL: "Corsair",
  CCM: "Air Corsica",
  FPO: "ASL Airlines France",
  DJT: "Air Djibouti",
  AIB: "Airbus Transport International",
  BGA: "Airbus Beluga Transport",
  CMA: "CMA CGM Air Cargo",
  BAW: "British Airways",
  EZY: "EasyJet",
  EJU: "EasyJet Europe",
  EXS: "Jet2",
  RUK: "Ryanair UK",
  RYR: "Ryanair",
  EIN: "Aer Lingus",
  LOG: "Loganair",
  BEE: "Flybe",
  IBE: "Iberia",
  VLG: "Vueling",
  VOE: "Volotea",
  ANE: "Air Nostrum",
  LAV: "Level",
  DLH: "Lufthansa",
  BER: "Eurowings",
  GWI: "Eurowings",
  CFG: "Condor",
  TUI: "TUI fly Germany",
  KLM: "KLM",
  BEL: "Brussels Airlines",
  SWR: "Swiss International Air Lines",
  AUA: "Austrian Airlines",
  HVN: "Transavia",
  TFL: "TUI fly Netherlands",
  AZA: "ITA Airways",
  ISS: "Air Italy",
  NEOS: "Neos",
  TAP: "TAP Air Portugal",
  PGA: "Portugalia Airlines",
  SAS: "Scandinavian Airlines",
  NAX: "Norwegian",
  NSZ: "Norwegian Sweden",
  WIF: "Widerøe",
  FLI: "Flyr",
  LOT: "LOT Polish Airlines",
  WZZ: "Wizz Air",
  TVS: "Smartwings",
  CSA: "Czech Airlines",
  AEE: "Aegean Airlines",
  TAR: "TAROM",
  THY: "Turkish Airlines",
  PGT: "Pegasus Airlines",
  FHY: "Freebird Airlines",
  UAE: "Emirates",
  QTR: "Qatar Airways",
  ETD: "Etihad Airways",
  SVA: "Saudia",
  MEA: "Middle East Airlines",
  RJA: "Royal Jordanian",
  OMA: "Oman Air",
  UAL: "United Airlines",
  AAL: "American Airlines",
  DAL: "Delta Air Lines",
  ACA: "Air Canada",
  SWA: "Southwest Airlines",
  JBU: "JetBlue",
  ASA: "Alaska Airlines",
  SIA: "Singapore Airlines",
  CPA: "Cathay Pacific",
  ANA: "All Nippon Airways",
  JAL: "Japan Airlines",
  KAL: "Korean Air",
  CCA: "Air China",
  CES: "China Eastern",
  CSN: "China Southern",
  THA: "Thai Airways",
  EVA: "EVA Air",
  RAM: "Royal Air Maroc",
  DAH: "Air Algérie",
  ETH: "Ethiopian Airlines",
  SAA: "South African Airways",
  MSR: "EgyptAir",
  UPS: "UPS Airlines",
  FDX: "FedEx",
  GTI: "Atlas Air",
  ABX: "ABX Air",
  CLX: "Cargolux",
  BOX: "European Air Transport",
  BCS: "European Air Transport",
  VJT: "VistaJet",
};